USE [ProjectSQL];
GO

CREATE TABLE [User]
	(
		[Id] INT IDENTITY(1,1) NOT NULL,
		[Login] NVARCHAR(200) NOT NULL,
		[Name] NVARCHAR(200) NOT NULL,
		[Mail] NVARCHAR(200) NOT NULL,
		[Key] NVARCHAR(255) NULL,
	);

ALTER TABLE [User] 
	ADD CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
	(
		[Id]
	);

ALTER TABLE [User] 
	ADD CONSTRAINT [IU_User_Login] UNIQUE NONCLUSTERED 
	(
		[Login]
	);

ALTER TABLE [User] 
	ADD CONSTRAINT [IU_User_Key] UNIQUE NONCLUSTERED 
	(
		[Key]
	);